// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trabajo_Final___Grupo_4.Data;

namespace Trabajo_Final___Grupo_4.Migrations
{
    [DbContext(typeof(UsuarioContext))]
    [Migration("20210725221502_inicial")]
    partial class inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Trabajo_Final___Grupo_4.Models.Alojamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Banios")
                        .HasColumnType("int");

                    b.Property<string>("Barrio")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("CantidadDePersonas")
                        .HasColumnType("int");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Estrellas")
                        .HasColumnType("int");

                    b.Property<int>("Habitaciones")
                        .HasColumnType("int");

                    b.Property<double>("PrecioPorDia")
                        .HasColumnType("double");

                    b.Property<double>("PrecioPorPersona")
                        .HasColumnType("double");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<bool>("Tv")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Alojamiento");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Banios = 0,
                            Barrio = "Recoleta",
                            CantidadDePersonas = 2,
                            Ciudad = "Buenos Aires",
                            Codigo = "352234",
                            Estrellas = 3,
                            Habitaciones = 0,
                            PrecioPorDia = 0.0,
                            PrecioPorPersona = 2400.0,
                            Tipo = "hotel",
                            Tv = true
                        },
                        new
                        {
                            Id = 2,
                            Banios = 2,
                            Barrio = "Sur",
                            CantidadDePersonas = 2,
                            Ciudad = "Neuquen",
                            Codigo = "934120",
                            Estrellas = 4,
                            Habitaciones = 4,
                            PrecioPorDia = 1200.0,
                            PrecioPorPersona = 0.0,
                            Tipo = "cabaña",
                            Tv = true
                        },
                        new
                        {
                            Id = 3,
                            Banios = 0,
                            Barrio = "Puerto Madero",
                            CantidadDePersonas = 2,
                            Ciudad = "Buenos Aires",
                            Codigo = "846445",
                            Estrellas = 2,
                            Habitaciones = 0,
                            PrecioPorDia = 0.0,
                            PrecioPorPersona = 6400.0,
                            Tipo = "hotel",
                            Tv = true
                        },
                        new
                        {
                            Id = 4,
                            Banios = 1,
                            Barrio = "Centro",
                            CantidadDePersonas = 5,
                            Ciudad = "Carlos Paz",
                            Codigo = "321632",
                            Estrellas = 1,
                            Habitaciones = 1,
                            PrecioPorDia = 2800.0,
                            PrecioPorPersona = 0.0,
                            Tipo = "cabaña",
                            Tv = true
                        });
                });

            modelBuilder.Entity("Trabajo_Final___Grupo_4.Models.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AlojamientoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaDesde")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaHasta")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("Precio")
                        .HasColumnType("double");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlojamientoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Reserva");
                });

            modelBuilder.Entity("Trabajo_Final___Grupo_4.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Bloqueado")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Dni")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<int>("Intentos")
                        .HasColumnType("int");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Dni")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bloqueado = false,
                            Dni = 1234,
                            Email = "admin@admin.com",
                            Intentos = 0,
                            IsAdmin = true,
                            Nombre = "admin",
                            Password = "03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4"
                        },
                        new
                        {
                            Id = 2,
                            Bloqueado = false,
                            Dni = 12312312,
                            Email = "prueba1@gmail.com",
                            Intentos = 0,
                            IsAdmin = false,
                            Nombre = "prueba1",
                            Password = "03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4"
                        },
                        new
                        {
                            Id = 3,
                            Bloqueado = true,
                            Dni = 23423423,
                            Email = "prueba2@gmail.com",
                            Intentos = 0,
                            IsAdmin = false,
                            Nombre = "prueba2",
                            Password = "03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4"
                        },
                        new
                        {
                            Id = 4,
                            Bloqueado = false,
                            Dni = 34534534,
                            Email = "prueba3@gmail.com",
                            Intentos = 0,
                            IsAdmin = false,
                            Nombre = "prueba3",
                            Password = "03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4"
                        });
                });

            modelBuilder.Entity("Trabajo_Final___Grupo_4.Models.Reserva", b =>
                {
                    b.HasOne("Trabajo_Final___Grupo_4.Models.Alojamiento", "Alojamiento")
                        .WithMany()
                        .HasForeignKey("AlojamientoId");

                    b.HasOne("Trabajo_Final___Grupo_4.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");
                });
#pragma warning restore 612, 618
        }
    }
}
